language: php
sudo: required

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2

before_install:
- composer install

script:
- composer cs-ci
- composer test